services:
  db:
    image: postgres:16
    container_name: postgres_dev
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data    
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
